apiVersion: v1
kind: Pod
metadata:
    name: docker-demo
spec:
  containers:
      - name: docker-demo
        image: us.gcr.io/[YOUR PROJECT ID HERE]/docker-demo
        imagePullPolicy: Always
        ports:
          - containerPort: 80
            hostPort: 80

